image: docker:latest

services:
  - docker:dind

stages:
- build
- deploy

variables:
  #CONTAINER_TEST_IMAGE: my-docker-hub/$CI_PROJECT_ID:$CI_BUILD_REF_NAME_test
  # The following variables are setup via gitlab project group:
  # DOCKER_HUB_TOKEN
  # DOCKER_USERNAME
  # DOCKER_PASSWORD
  # INTERNAL_REGISTRY_HOST
  # INTERNAL_REGISTRY_USER
  # INTERNAL_REGISTRY_PW
  VERSION: "1.0-debian"

before_script:
- apk add --no-cache make bash sudo git
- docker login -u "$INTERNAL_REGISTRY_USER" -p "$INTERNAL_REGISTRY_PW" "$INTERNAL_REGISTRY_HOST"
#- make install

.build:
  stage: build
  only: 
  - master  
  script:
  - make build v=$VERSION
  - make tags
  - make push

include:
  - '.legacy/.gitlab-ci.yml'
  - '1.0-debian/.gitlab-ci.yml'
  - '1.1-debian/.gitlab-ci.yml'
  - '1.2-debian/.gitlab-ci.yml'

# after_success:
# # notify Docker Hub to make a new build
#   only: master
#   - make notify-hub-docker-com TOKEN=$DOCKER_HUB_TOKEN