image: docker:latest

services:
  - docker:dind

stages:
- test
- build

variables:
  # The following variables are setup via gitlab project group:
  # DOCKER_HUB_TOKEN
  # DOCKER_SLUG
  # DOCKER_USERNAME
  # DOCKER_PASSWORD
  # CUSTOM_REGISTRY_URL
  # CUSTOM_REGISTRY_USER
  # CUSTOM_REGISTRY_PW
  DOCKER_DRIVER: overlay2

before_script:
- .ci/01_before_install.sh

.test:
  stage: test
  except: 
  - master  
  script:
  - make -C .ci  build v=$VERSION

.build:
  stage: build
  only: 
  - master  
  - bug/MDD179
  script:
  - make -C .ci  build v=$VERSION
  - make -C .ci  tags REPOURL=$DOCKER_SLUG
  - make -C .ci  tags REPOURL=$CUSTOM_REGISTRY_URL
  - make -C .ci  push REPOURL=$CUSTOM_REGISTRY_URL USER=$CUSTOM_REGISTRY_USER PW=$CUSTOM_REGISTRY_PW
  - make -C .ci  push REPOURL=$DOCKER_SLUG USER=$DOCKER_USERNAME PW=$DOCKER_PASSWORD
  - make -C .ci  notify-hub-docker-com TOKEN=$DOCKER_HUB_TOKEN

#
# For a cleaner Gitlab CI file include all subfolder which should be build:
#
include:
  - '.legacy/.gitlab-ci.yml'
  - '1.0-debian/.gitlab-ci.yml'
  - '1.1-debian/.gitlab-ci.yml'
  - '1.2-debian/.gitlab-ci.yml'
  - '1.3-debian/.gitlab-ci.yml'
