dist: xenial
addons:
  apt:
    sources:
      - docker-xenial

env:
  global:
  # The following variables are setup via gitlab project group:
  # - DOCKER_HUB_TOKEN
  # - DOCKER_SLUG
  # - DOCKER_USERNAME
  # - DOCKER_PASSWORD
  # - CUSTOM_REGISTRY_URL
  # - CUSTOM_REGISTRY_USER
  # - CUSTOM_REGISTRY_PWs
  matrix:
  - VERSION=1.0-debian
  - VERSION=1.1-debian
  - VERSION=1.2-debian
  - VERSION=1.3-debian
  #- VERSION=2.0-alpine
  # legacy
  - VERSION=1.0.0-debian
  - VERSION=1.0.1-debian

before_install:
- sudo .ci/01_before_install.sh

script:
- make -C .ci  build v=${VERSION}
- make -C .ci  tags REPOURL=$DOCKER_SLUG # tagged dcso/CONTAINERNAME + custom-URL/CONTAINERNAME

# don't notify me when things fail
notifications:
  email: false